apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-cache
  namespace: arc-runners
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: hyperdisk-balanced-sc
  volumeMode: Filesystem
