apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: tpu-v7
spec:
  nodeLabels:
    cloud.google.com/gke-tpu-accelerator: tpu7x
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: tpu-cluster-queue
spec:
  namespaceSelector: {} # Allow all namespaces
  resourceGroups:
  - coveredResources: ["google.com/tpu", "cpu", "memory"]
    flavors:
    - name: tpu-v7
      resources:
      - name: "google.com/tpu"
        nominalQuota: 8 # Limit to 8 TPU chips (2 node slices)
      - name: "cpu"
        nominalQuota: 1000 # High cpu nominal quota for cluster TPU hosts
      - name: "memory"
        nominalQuota: 4000Gi # High memory nominal quota for cluster TPU hosts
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: tpu-inferencex-jobs
  namespace: inferencex-jobs
spec:
  clusterQueue: tpu-cluster-queue
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-shared-cache-pvc
  namespace: inferencex-jobs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 1000Gi
